---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install nginx, tomcat8, maven and OpenJDK at their latest version
      become: yes
      apt: name={{item}} state=latest
      with_items:
          - nginx
          - tomcat8
          - maven
          - openjdk-8-jdk 
          - openjdk-8-jre
          - openjdk-8-jdk-headless
          - openjdk-8-jre-headless
      retries: 3

    - name: start nginx
      service:
          name: nginx
          state: started
          enabled: yes

    - name: start tomcat8
      service:
          name: tomcat8
          state: started
          enabled: yes


    - name: Create /opt/spring directory if it does not exist
      become: yes
      file:
        path: /opt/spring
        state: directory
        mode: '0755'
        owner: 'root'

    - name: Downloading and unpacking Spring Boot CLI
      become: yes
      unarchive:
        src: "https://repo.spring.io/release/org/springframework/boot/spring-boot-cli/2.1.4.RELEASE/spring-boot-cli-2.1.4.RELEASE-bin.tar.gz"
        dest: "/opt/spring"
        copy: no

    - name: Adding SPRING to PATH
      shell: echo "PATH=$PATH:/opt/spring-boot/spring-2.1.4.RELEASE" >> /etc/environment
      become: true

    - name: Adding SPRING_HOME to environment
      shell: echo "SPRING_HOME=/opt/spring-boot/spring-2.1.4.RELEASE" >> /etc/environment
      become: true

    - name: Set up authorized keys
      become: yes
      authorized_key:
        user: ubuntu
        state: present
        key: '{{ item }}'
      with_file:
        - 'files/ssh_keys/diana_fndz.pub'  
        - 'files/ssh_keys/eduardo_garcia.pub'   
        - 'files/ssh_keys/oliver_rojo.pub'      
        - 'files/ssh_keys/orlando_flores.pub'    
        - 'files/ssh_keys/pablo_ramirez.pub'     
        - 'files/ssh_keys/rafael_rojas.pub'                                
        - 'files/ssh_keys/sergio_nunez.pub' 
        - 'files/appserver_key.pub'

    - name: Setup JavaApp private keys
      become: yes
      copy: 
        src: files/appserver_key
        dest: /home/ubuntu/.ssh/
        owner: ubuntu
        group: ubuntu
        mode: 0600 
